name: flutterdemo
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluro: ^1.6.0
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  dio_cookie_manager: ^1.0.0
  fluttertoast: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true